# Principal Component Analysis

### Importing The Librararies

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA


## Scalling the Data to speed up computing performance

In [12]:
dataset=pd.read_csv('Wine.csv')
X=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values
sc=StandardScaler()
X=sc.fit_transform(X)

## Splitting the dataset into the Training set and Test set

In [13]:

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)


## Applying the PCA Algorithm on data

In [17]:
pca=PCA(n_components=2)
X_train=pca.fit_transform(X_train)
X_test =pca.transform(X_test)
explained_variance = pca.explained_variance_ratio_

In [18]:
# Training the Logistic Regression model on the Training set
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[14  0  0]
 [ 1 15  0]
 [ 0  0  6]]
