## Importing the Libraries



In [49]:
import numpy as np 
import pandas as pd 
from sklearn.impute import SimpleImputer 
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score

## Importing Data


In [17]:
dataset=pd.read_csv('https://raw.githubusercontent.com/jbrownlee/Datasets/master/breast-cancer-wisconsin.csv',header=None)
dataset.head(10)

0   1   2  3  4   5  6  7  8  9
0  5   1   1  1  2   1  3  1  1  2
1  5   4   4  5  7  10  3  2  1  2
2  3   1   1  1  2   2  3  1  1  2
3  6   8   8  1  3   4  3  7  1  2
4  4   1   1  3  2   1  3  1  1  2
5  8  10  10  8  7  10  9  7  1  4
6  1   1   1  1  2  10  3  1  1  2
7  2   1   2  1  2   1  3  1  1  2
8  2   1   1  1  2   1  1  1  5  2
9  4   2   1  1  2   1  2  1  1  2

In [18]:
dataset.columns=['Clump Thickness','Uniformity of Cell Size','Uniformity of Cell Shape ',
                     ' Marginal Adhesion','Single Epithelial Cell Size','Bare Nuclei','Bland Chromatin','Normal Nucleoli'
             ,'Mitoses','diagnosis']
dataset.diagnosis[dataset.diagnosis==4]=1
dataset.diagnosis[dataset.diagnosis==2]=0
dataset.head(10)

/home/hussein/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/home/hussein/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """


Clump Thickness  Uniformity of Cell Size  Uniformity of Cell Shape   \
0                5                        1                          1   
1                5                        4                          4   
2                3                        1                          1   
3                6                        8                          8   
4                4                        1                          1   
5                8                       10                         10   
6                1                        1                          1   
7                2                        1                          2   
8                2                        1                          1   
9                4                        2                          1   

    Marginal Adhesion  Single Epithelial Cell Size Bare Nuclei  \
0                   1                            2           1   
1                   5                            7          10   
2                   1                            2           2   
3                   1                            3           4   
4                   3                            2           1   
5                   8                            7          10   
6                   1                            2          10   
7                   1                            2           1   
8                   1                            2           1   
9                   1                            2           1   

   Bland Chromatin  Normal Nucleoli  Mitoses  diagnosis  
0                3                1        1          0  
1                3                2        1          0  
2                3                1        1          0  
3                3                7        1          0  
4                3                1        1          0  
5                9                7        1          1  
6                3                1        1          0  
7                3                1        1          0  
8                1                1        5          0  
9                2                1        1          0

## Handling Missing Values


In [19]:
X=dataset.iloc[:,:-1].values
y=dataset.iloc[:, -1].values
#to replace ? with nan values and and then handle it using SimpleImputer
#NumpyArray.shape: return tuble of (Rows, Cols)
for i in range(X.shape[0]):
  for j in range(X.shape[1]):
    if X[i][j]=='?':
      X[i][j]=np.nan

In [20]:
#detect the missing values in columns
print(pd.DataFrame(X).isnull().sum())

0     0
1     0
2     0
3     0
4     0
5    16
6     0
7     0
8     0
dtype: int64


In [21]:
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit(X)
X=imputer.fit_transform(X)
print(pd.DataFrame(X).isnull().sum())

0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
dtype: int64


## Feature Scalling 

In [22]:
sc=StandardScaler()
sc.fit(X)
X=sc.transform(X)

## Spliting The Data into Train and Test

In [23]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

## Train Logistic Regession Classifier

In [31]:
logistic_regressor=LogisticRegression(random_state=0)
logistic_regressor.fit(X_train,y_train)
y_pred=logistic_regressor.predict(X_test)
y_pred

array([0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 0])

#### Evaluating Accuracy using K-fold cross Validation

In [29]:
accuracies=cross_val_score(estimator=logistic_regressor,X=X_train,y=y_train,cv=10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 96.43 %
Standard Deviation: 2.52 %


## Train KnearestNeighbors Classifier

In [35]:
KNN_classifier=KNeighborsClassifier(n_neighbors=5,p=2,metric = 'minkowski')
KNN_classifier.fit(X_train,y_train)
y_pred=KNN_classifier.predict(X_test)
y_pred

array([0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 0])

#### Evaluating Accuracy using K-fold cross Validation

In [39]:
accuracies=cross_val_score(estimator=KNN_classifier,X=X_train,y=y_train,cv=10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 96.43 %
Standard Deviation: 3.29 %


## Train NaiveBayes Classifier

In [37]:
NB_classifier=GaussianNB()
NB_classifier.fit(X_train,y_train)
y_pred=NB_classifier.predict(X_test)
y_pred

array([0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 0])

#### Evaluating Accuracy using K-fold cross Validation

In [38]:
accuracies=cross_val_score(estimator=NB_classifier,X=X_train,y=y_train,cv=10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 96.25 %
Standard Deviation: 2.82 %


## Train RandomForest Classifier

In [42]:
RF_classifier=RandomForestClassifier(n_estimators=100,criterion='entropy',random_state=0)
RF_classifier.fit(X_train,y_train)
y_pred=RF_classifier.predict(X_test)
y_pred

array([0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 0])

#### Evaluating Accuracy using K-fold cross Validation

In [44]:
accuracies=cross_val_score(estimator=RF_classifier,X=X_train,y=y_train,cv=10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 96.06 %
Standard Deviation: 2.51 %


## Train DecisionTrees Classifier

In [45]:
DT_classifier=DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
DT_classifier.fit(X_train,y_train)
y_pred=DT_classifier.predict(X_test)
y_pred

array([0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 0])

#### Evaluating Accuracy using K-fold cross Validation

In [47]:
accuracies=cross_val_score(estimator=DT_classifier,X=X_train,y=y_train,cv=10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 93.92 %
Standard Deviation: 2.15 %
